import React, { useMemo } from 'react';
import { GenerationStatus } from '../types';
import LoadingSpinner from './LoadingSpinner';

interface SvgDisplayProps {
  status: GenerationStatus;
  svgContent: string;
  error: string | null;
}

const SvgDisplay: React.FC<SvgDisplayProps> = ({ status, svgContent, error }) => {
  
  const downloadSvg = () => {
    if (!svgContent) return;
    const blob = new Blob([svgContent], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generated-image.svg';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copyCode = () => {
    if(!svgContent) return;
    navigator.clipboard.writeText(svgContent);
    alert("SVG Code copied to clipboard!");
  };

  // Safe render of SVG using dangerous HTML, assuming source is trusted (our own API/Sanitization)
  const renderSvg = useMemo(() => {
    return { __html: svgContent };
  }, [svgContent]);

  return (
    <div className="w-full h-full flex flex-col">
      {/* Viewport Area */}
      <div className="flex-grow bg-[#1e293b] rounded-xl border-2 border-[#334155] overflow-hidden flex items-center justify-center relative min-h-[400px]">
        
        {/* Grid Background Pattern */}
        <div 
          className="absolute inset-0 opacity-20 pointer-events-none" 
          style={{ 
            backgroundImage: 'radial-gradient(#64748b 1px, transparent 1px)', 
            backgroundSize: '20px 20px' 
          }}
        ></div>

        {status === GenerationStatus.IDLE && (
          <div className="text-slate-400 text-center p-6">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mx-auto mb-4 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            <p className="text-lg">Enter a prompt to generate an SVG.</p>
          </div>
        )}

        {status === GenerationStatus.LOADING && <LoadingSpinner />}

        {status === GenerationStatus.ERROR && (
          <div className="text-red-400 text-center p-6 max-w-md">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p className="font-semibold">Generation Failed</p>
            <p className="text-sm mt-2 opacity-80">{error}</p>
          </div>
        )}

        {status === GenerationStatus.SUCCESS && svgContent && (
          <div 
            className="w-full h-full p-8 flex items-center justify-center animate-in fade-in duration-700"
            dangerouslySetInnerHTML={renderSvg}
          />
        )}
      </div>

      {/* Action Bar */}
      {status === GenerationStatus.SUCCESS && (
        <div className="mt-4 flex flex-wrap gap-4 justify-between items-center">
          <div className="flex gap-3">
             <button 
              onClick={downloadSvg}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-medium transition-colors text-sm"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              Download SVG
            </button>
            <button 
              onClick={copyCode}
              className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded-lg font-medium transition-colors text-sm"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Copy Code
            </button>
          </div>
          <div className="text-xs text-slate-500 font-mono">
            Generated by Gemini 3 Pro
          </div>
        </div>
      )}
    </div>
  );
};

export default SvgDisplay;